version: "3"
services:
  rclrs-dev:
    build: .
    volumes:
      - type: bind
        source: "../"
        target: "/home/vscode/workspace"
      - type: bind
        source: "~/.ssh"
        target: "/home/vscode/.ssh"
    cap_add: 
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    command: /bin/sh -c "sleep infinity"